# This file was generated by GoReleaser. DO NOT EDIT.
cask "devproxy" do
  name "devproxy"
  desc "Local development reverse proxy with automatic TLS and Docker integration"
  homepage "https://github.com/munichmade/devproxy"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devproxy"

  on_macos do
    on_intel do
      url "https://github.com/munichmade/devproxy/releases/download/v#{version}/devproxy-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/munichmade/devproxy"
      sha256 "ce3753a06179fb25dad2b826f276ab960ed0a893f9c97ce010f4e99cd5cda315"
    end
    on_arm do
      url "https://github.com/munichmade/devproxy/releases/download/v#{version}/devproxy-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/munichmade/devproxy"
      sha256 "72c7dd4a7ab7fca4d0d088e4838ca9336b13895b610cc55c7a9ccd43f151f677"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/munichmade/devproxy/releases/download/v#{version}/devproxy-#{version}-linux-amd64.tar.gz",
        verified: "github.com/munichmade/devproxy"
      sha256 "e6b88a2ca47e9f95d5d9dce86819730a07c208646a7254d89ce738994f9910ce"
    end
    on_arm do
      url "https://github.com/munichmade/devproxy/releases/download/v#{version}/devproxy-#{version}-linux-arm64.tar.gz",
        verified: "github.com/munichmade/devproxy"
      sha256 "131158c188fd908578bc7d3474548a8ab4edd3a715b129e6cc87df84bcd50cd2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devproxy"]
    end
  end

  # No zap stanza required
end
