# This file was generated by GoReleaser. DO NOT EDIT.
cask "devproxy" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "5a43b6d707e05088879ab79956cca551e5141e0404d7c842a22e4d2eb6daa094"
      url "https://github.com/munichmade/devproxy/releases/download/v#{version}/devproxy-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/munichmade/devproxy"
    end
    on_arm do
      sha256 "09c07c64fd321875dce665f0f5d3f1ecdbcfad376f5a74dd83d175640216c1c5"
      url "https://github.com/munichmade/devproxy/releases/download/v#{version}/devproxy-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/munichmade/devproxy"
    end
  end

  on_linux do
    on_intel do
      sha256 "9a3a73160b0b4d88ae783da369c3947eccbeeffe26f765700b1b4169b3932091"
      url "https://github.com/munichmade/devproxy/releases/download/v#{version}/devproxy-#{version}-linux-amd64.tar.gz",
        verified: "github.com/munichmade/devproxy"
    end
    on_arm do
      sha256 "4a7c1211576b920d4b82aaceaaa323770384083bb782cdd6003e7045c8a57c3e"
      url "https://github.com/munichmade/devproxy/releases/download/v#{version}/devproxy-#{version}-linux-arm64.tar.gz",
        verified: "github.com/munichmade/devproxy"
    end
  end

  name "devproxy"
  desc "Local development reverse proxy with automatic TLS and Docker integration"
  homepage "https://github.com/munichmade/devproxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devproxy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devproxy"]
    end
  end

  # No zap stanza required

end
